# Generated by Django 5.0 on 2024-04-17 05:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_category_subcategory_subsubcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
