# Generated by Django 5.0 on 2024-04-17 05:55

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_shop_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='decoration',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='subsubcategory',
            name='description',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
