# Generated by Django 5.0 on 2024-04-17 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_decoration_description_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brownie',
        ),
        migrations.DeleteModel(
            name='Cake',
        ),
        migrations.DeleteModel(
            name='Cupcake',
        ),
        migrations.DeleteModel(
            name='Weddingcake',
        ),
    ]
